# Generated by Django 4.2 on 2023-05-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourregistration",
            name="age",
            field=models.PositiveIntegerField(blank=True, max_length=2, null=True),
        ),
    ]
