# Generated by Django 4.2 on 2023-06-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tourregistration_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourregistration',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
